### ISSUE TITLE
Write README tutorial

### ISSUE THREAD

**Issue by chshersh** [Holmusk/cake-slayer#11]
Motivation behind this library, how to use it, etc.

Things to mention in README:

- [ ] Badges
- [ ] Short description
- [ ] Libraries used and with what libraries integration is provided
- [ ] Short description of the approach with steps (with links to modules)

**Comment by arbus** [comment]
We can consider creating something like a stack template as a quick-start as well

**Comment by chshersh** [comment]
@arbus We can do even better! @vrom911 told me that there is _GitHub repo template_ feature. So we can create `cake-slayer-template` repo and mark it as a template repo so everyone can create their own project directly from GitHub. This approach has the following benefits:

1. Doesn't restrict you to use `stack` build tool only and works for `cabal` as well
2. Creates GitHub repo as well, not only locally
3. Much easier and saner to maintain than `stack` templates
