### ISSUE TITLE
Bring time module

### ISSUE THREAD

**Issue by chshersh** [Holmusk/cake-slayer#20]
We usually define `newtype Seconds` in our projects. Should we create `CakeSlayer.Time` module? It can contain:

- [x] `newtype Seconds`
- [ ] ~~`newtype ElmTime`~~
- [x] `dayInSeconds`
- [x] `threadDelay`
- [x] Various pure functions to work with UTCTime
- [x] Can be used in JWT tokens generation

**Comment by vrom911** [comment]
This is quite useful!

But most importantly I would like to see our `proto`-related function. Do you know if it would be possible to reuse common-proto files? ((I think it is not possible, but, maybe you have any ideas). At least we can write general functions that could use `HasField "blaBla" Foo`, if that makes any sense to do.

**Comment by vrom911** [comment]
I don't think that ElmTime should be in the library. We can use encoders and decoders to frontend `Posix` implemented in `elm-street` if we need `UTCTime` on the frontend. What do you think?

**Comment by chshersh** [comment]
@vrom911 I agree that functions to work with Protocol Buffers are the most useful. But they will have huge `HasField` constraints from `proto-lens` library... Maybe it's simpler to include them in `cake-slayer-template`?

Regarding ElmTime: agree, `elm-street` can take care of it.

**Comment by vrom911** [comment]
This sounds strange. `cake-slayer-template`?

**Comment by chshersh** [comment]
@vrom911 Well, the idea was to create a scaffolding repository that depends on `cake-slayer` and implements something minimal. In `cake-slayer` we try to abstract as much as possible. But, for example, users of `cake-slayer` still need to define their errors data type and specialise our types to their monomorphic types. So I just thought it could be a good idea to implement `cake-slayer-template` repo using GitHub templates feature so users can create their project in one click...

But I agree that general idea behind `cake-slayer` -- be a batteries-included framework -- should not rely on the existing of the template and in ideal worlds this template should not exist. So if we can put as much as possible to `cake-slayer`, that would be great! And it seems like functions to work with protocol buffers time can be put into `cake-slayer`.
