### ISSUE TITLE
Implement `MonadJwt` effect

### ISSUE THREAD

**Issue by chshersh** [Holmusk/cake-slayer#7]
- [ ] Jwt data types and functions
- [ ] `MonadJwt` effect
- [ ] Roundtrip tests

**Comment by chshersh** [comment]
@vrom911 Do you have any suggestions on how we should structure this in the library? In projects we have `Core.Jwt` and `Effect.Jwt` modules. But I think that the same separation doesn't make much sense here.

I have the following options in mind:

* Just `CakeSlayer.Jwt`
* `CakeSlayer.Effect.Jwt`: everything is here
* `CakeSlayer.Jwt`, `CakeSlayer.Jwt.Type` (or `Core` instead of `Type`) and `CakeSlayer.Jwt.Effect`

What do you think?

**Comment by vrom911** [comment]
It's either 1 or the last one. I don't think that the second one is helpful enough for the library structure understanding.
