### ISSUE TITLE
Implement DB functions

### ISSUE THREAD

**Issue by chshersh** [Holmusk/cake-slayer#9]
**Question 1:** should we have only `*named` and `Raw` functions?
**Question 2:** Should we create `MonadDb` typeclass and implement as typeclass methods instead of `WithDb` constraint?

**Comment by arbus** [comment]
In the spirit of this being a more general library, there is an extra constraint that we should consider: more than one DB that we can connect to.

eg scenerio: As a product starts scaling, we might need to run the backend in more than one region. In most typical scenerios, there will be a lot more `SELECT` statements than `INSERT` or `UPDATE` statements, so we can add extra read slaves of the main db in those regions.

Having the ability to specify multiple DB connections and which one a particular call to `query` or `execute` should run against would be a great feature to have.

**Comment by chshersh** [comment]
@arbus I think this is a separate feature request and design for this feature should be implemented separately, not as a part of moving reusable parts into the library. Also, this problem is non-trivial and will require some thinking. I don't want this issue to be blocked while we're looking for the proper solution.

**Comment by arbus** [comment]
Fair enough, lets think on the design for this a bit more

**Comment by vrom911** [comment]
I like the way we have `WithDB` at the moment, so I would stick with that.

**Comment by chshersh** [comment]
@vrom911 Okay, agree. One step at a time. Let's just move things first to see how they go and refactor later when needed.
